### ISSUE TITLE
[FIXED] Kaboom

### ISSUE THREAD

**Issue by sergeevabc** [mcychan/nQuantCpp#1]
Windows 7 x64, nQuantCpp 1.06, [image.png][1]

```
$ nQuantCpp.exe image.png /m 128
Converted image: C:\Test\image-DIVquant128.png
Converted image: C:\Test\image-PNNquant128.png
Converted image: C:\Test\image-NEUquant128.png
```

And then suddenly… Kaboom!

![](https://i5.imageban.ru/out/2019/04/24/1111f064ed807b9d4f81b9a8a48cc54f.png)

[1]: https://linx.li/s/image2.png

**Comment by mcychan** [comment]
fixed at nQuantCpp 1.07
