### ISSUE TITLE
Logic error

### ISSUE THREAD

**Issue by byian** [mcychan/nQuantCpp#2]
https://github.com/mcychan/nQuantCpp/blob/e89c1a23b13d181a6ff3fef50110856c9b7cf4c9/nQuantCpp/PnnQuantizer.cpp#L114

`extbins` become negative if `nMaxColors` greater then `maxbins`

maybe should use absolute value?

`uint extbins = std::abs(maxbins - nMaxColors); `

**Comment by mcychan** [comment]
Not required to use absolute value because it accepts all colors from the original image in such case.
