### ISSUE TITLE
DL3 algorithm not available in exe

### ISSUE THREAD

**Issue by Jsfasdf250** [mcychan/nQuantCpp#5]
There doesn't seem to be an option to quantize using the Dennis Lee v3 algorithm in the executable. The options listed are PNN, PNNLAB, NEU, WU, EAS, SPA, DIV, MMC, OTSU, but none of them seem to be for that algorithm. If it actually isn't available from the exe, could you add it?

**Comment by mcychan** [comment]
I removed DL3 because I was not able to deal with the division by zero bugs.
I added back that options but not release yet.
I forget where are the images making it throw division by zero error from the method calc_err.
